/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.kotlin.ui.internal.KotlinActivator;

public class KotlinUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return KotlinActivator.getInstance().getInjector("org.xtext.example.kotlin.Kotlin");
	}

}
