/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.ide;

import org.xtext.example.kotlin.ide.AbstractKotlinIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class KotlinIdeModule extends AbstractKotlinIdeModule {
}
