/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.kotlin.KotlinRuntimeModule;
import org.xtext.example.kotlin.KotlinStandaloneSetup;
import org.xtext.example.kotlin.ide.KotlinIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class KotlinIdeSetup extends KotlinStandaloneSetup {
  @Override
  public Injector createInjector() {
    KotlinRuntimeModule _kotlinRuntimeModule = new KotlinRuntimeModule();
    KotlinIdeModule _kotlinIdeModule = new KotlinIdeModule();
    return Guice.createInjector(Modules2.mixin(_kotlinRuntimeModule, _kotlinIdeModule));
  }
}
