/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractKotlinValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.kotlin.kotlin.KotlinPackage.eINSTANCE);
		return result;
	}
	
}
