/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.kotlin.ui.AbstractKotlinUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KotlinUiModule extends AbstractKotlinUiModule {
  public KotlinUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
