/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KotlinStandaloneSetup extends KotlinStandaloneSetupGenerated {

	def static void doSetup() {
		new KotlinStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
