/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.kotlin.parser.antlr.internal.InternalKotlinParser;
import org.xtext.example.kotlin.services.KotlinGrammarAccess;

public class KotlinParser extends AbstractAntlrParser {

	@Inject
	private KotlinGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKotlinParser createParser(XtextTokenStream stream) {
		return new InternalKotlinParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public KotlinGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KotlinGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
