/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.kotlin.ui.internal.KotlinActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KotlinExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KotlinActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KotlinActivator.getInstance().getInjector(KotlinActivator.ORG_XTEXT_EXAMPLE_KOTLIN_KOTLIN);
	}
	
}
