/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.kotlin;

import org.xtext.example.kotlin.KotlinStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KotlinStandaloneSetup extends KotlinStandaloneSetupGenerated {
  public static void doSetup() {
    new KotlinStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
